# Generated by Django 4.0.4 on 2022-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='free_photo'),
        ),
    ]
