# Generated by Django 4.0.4 on 2022-05-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pur',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('category', models.IntegerField(choices=[(0, '식재료'), (1, '생필품'), (2, 'OTT'), (3, '배달')], default=0)),
                ('wpeople', models.IntegerField()),
                ('peopole', models.IntegerField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('good', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
