# Generated by Django 4.0.4 on 2022-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pur',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='pur',
            name='long',
        ),
        migrations.AlterField(
            model_name='pur',
            name='good',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pur',
            name='peopole',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
