# Generated by Django 4.0.4 on 2022-05-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbd', '0002_remove_pur_lat_remove_pur_long_alter_pur_good_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pur',
            old_name='peopole',
            new_name='people',
        ),
    ]
