# Generated by Django 4.0.4 on 2022-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbd', '0003_rename_peopole_pur_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='pur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pur_photo'),
        ),
    ]
